a.out : add sub mul div
	gcc -o a.out myshell.c

add :
	gcc -o ./mybin/add ./mybin/add.c

sub :
	gcc -o ./mybin/sub ./mybin/sub.c

mul :
	gcc -o ./mybin/mul ./mybin/mul.c

div :
	gcc -o ./mybin/div ./mybin/div.c